sylius_user:
    resources:
        shop:
            user:
                classes:
                    model: Netgen\Bundle\EzSyliusBundle\Entity\ShopUser
        admin:
            user:
                classes:
                    model: Netgen\Bundle\EzSyliusBundle\Entity\AdminUser
