services:
    netgen_ez_sylius.repository.ez_sylius_user:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Netgen\Bundle\EzSyliusBundle\Entity\EzSyliusUser
