parameters:
    netgen_ez_sylius.entity.ez_sylius_user.class: Netgen\Bundle\EzSyliusBundle\Entity\EzSyliusUser

services:
    netgen_ez_sylius.repository.ez_sylius_user:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - "%netgen_ez_sylius.entity.ez_sylius_user.class%"
