parameters:
    security.authentication.success_handler.class: Netgen\Bundle\EzSyliusBundle\Authentication\AuthenticationSuccessHandler
    security.authentication.provider.dao.class: Netgen\Bundle\EzSyliusBundle\Authentication\DaoAuthenticationProvider

services:
    sylius.authentication.success_handler:
        class: Netgen\Bundle\EzSyliusBundle\Authentication\AuthenticationSuccessHandler
        parent: security.authentication.success_handler
        public: false
